# APP
spring.application.name=AUTH-SERVICE
server.port=8081

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service_db
spring.datasource.username=postgres
spring.datasource.password=Jfrc11$$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT CONFIGURATION
jwt.secret=d2lkZ2V0X3dkc2VjcmV0a2V5MjAyMzEyMzFhZWlvdXhjemd5d3pxcTEyMzQ1Njc4OTBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejA5OHc3ZjZlNQ==
jwt.expiration=86400000

# EMAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soportesistema.mk@gmail.com
spring.mail.password=gtzxzptemnkixrse
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=*

# LOGGING CONFIGURATION
logging.level.org.springframework.security=DEBUG

# REDIS - CACHEO Y SESIONES
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0
spring.data.redis.jedis.pool.max-wait=-1ms

# EUREKA - SERVICE DISCOVERY
eureka.client.enabled=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ACTUATOR - MONITOREO
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
